"use server";

import { revalidatePath } from "next/cache";

import { createClient } from "@/lib/supabase/server";
import { createProviderOrder, getProviderOrders, ProviderOrderRejectedError, type ProviderCatalogType } from "@/lib/provider";
import { readPlatformStatus } from "@/lib/platform-status";

interface SupplierJob { id:string;order_id:string;order_item_id:string;product_id:string|null;offer_id:string|null;provider_offer_id:string|null;supplier_product_id:string|null;input_values:Record<string,string>|null;status:string;attempts_count:number; }
interface ProviderDataRow { provider_data:Record<string,unknown>|null; }

async function requireAdmin(){const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("Authentication required");const{data:profile}=await supabase.from("profiles").select("role,status").eq("id",user.id).single<{role:string;status:string}>();if(!profile||profile.status!=="active"||!["admin","super_admin","owner"].includes(profile.role))throw new Error("Admin permission required");return{supabase,adminId:user.id}}

function catalogType(...sources:Array<Record<string,unknown>|null|undefined>):ProviderCatalogType|null{for(const source of sources){const value=source?.catalog_type;if(value==="topup"||value==="gc")return value}return null}
function targetAccount(values:Record<string,string>,...sources:Array<Record<string,unknown>|null|undefined>):string|null{const direct=values.target_account?.trim();if(direct)return direct;for(const source of sources){const field=source?.target_account_field;if(typeof field==="string"&&values[field]?.trim())return values[field].trim()}const nonEmpty=Object.values(values).map(v=>String(v).trim()).filter(Boolean);return nonEmpty.length===1?nonEmpty[0]:null}

async function refreshAggregate(supabase:Awaited<ReturnType<typeof createClient>>,job:SupplierJob){const{data:itemJobs}=await supabase.from("product_supplier_jobs").select("id,status,supplier_order_id,supplier_status,supplier_response,last_error").eq("order_item_id",job.order_item_id);const rows=itemJobs??[];const itemStatus=rows.length>0&&rows.every(row=>row.status==="completed")?"completed":rows.some(row=>row.status==="failed")?"manual_review":"supplier_pending";await supabase.from("product_order_items").update({status:itemStatus,supplier_response:{jobs:rows},updated_at:new Date().toISOString()}).eq("id",job.order_item_id);const{data:orderJobs}=await supabase.from("product_supplier_jobs").select("status").eq("order_id",job.order_id);const all=orderJobs??[];const orderStatus=all.length>0&&all.every(row=>row.status==="completed")?"completed":all.some(row=>row.status==="failed")?"manual_review":"supplier_pending";await supabase.rpc("admin_update_product_order_status",{p_order_id:job.order_id,p_new_status:orderStatus,p_note:orderStatus==="completed"?"All supplier jobs completed successfully":orderStatus==="manual_review"?"Supplier job requires manual review":"Order sent to supplier"});}

async function processJob(supabase:Awaited<ReturnType<typeof createClient>>,job:SupplierJob){if(!job.offer_id||!job.provider_offer_id)throw new Error("Supplier job is missing offer identifiers");const[offerR,productR]=await Promise.all([supabase.from("store_product_offers").select("provider_data").eq("id",job.offer_id).single<ProviderDataRow>(),job.product_id?supabase.from("store_products").select("provider_data").eq("id",job.product_id).single<ProviderDataRow>():Promise.resolve({data:null,error:null})]);const offerData=offerR.data?.provider_data;const productData=productR.data?.provider_data;const type=catalogType(offerData,productData);if(!type)throw new Error("Provider catalog type is missing");const providerProductId=job.supplier_product_id?.trim()||(typeof productData?.provider_category_id==="string"?productData.provider_category_id.trim():"");if(!providerProductId)throw new Error("Provider product ID is missing");const inputs=job.input_values??{};const target=type==="topup"?targetAccount(inputs,offerData,productData):null;if(type==="topup"&&!target)throw new Error("Topup target account is ambiguous. Configure target_account_field for this offer.");
  const{data:claimed}=await supabase.from("product_supplier_jobs").update({status:"sending",attempts_count:job.attempts_count+1,last_error:null,updated_at:new Date().toISOString()}).eq("id",job.id).eq("status","pending").select("id").maybeSingle();if(!claimed)return{sent:false,status:"skipped",message:"Job was already claimed"};
  try{const result=await createProviderOrder({type,productId:providerProductId,offerId:job.provider_offer_id,quantity:1,targetAccount:target??undefined});const completed=["completed","success"].includes(result.order.status);await supabase.from("product_supplier_jobs").update({status:completed?"completed":"supplier_pending",supplier_order_id:result.order.fazerOrderId,supplier_status:result.order.status,supplier_response:result.raw,sent_at:new Date().toISOString(),completed_at:completed?new Date().toISOString():null,updated_at:new Date().toISOString()}).eq("id",job.id);await refreshAggregate(supabase,job);return{sent:true,status:completed?"completed":"supplier_pending",message:result.order.fazerOrderId};}
  catch(error){if(error instanceof ProviderOrderRejectedError){await supabase.from("product_supplier_jobs").update({status:"failed",supplier_status:error.code,supplier_response:error.response,last_error:error.message,updated_at:new Date().toISOString()}).eq("id",job.id);await refreshAggregate(supabase,job);return{sent:false,status:"failed",message:error.message}}await supabase.from("product_supplier_jobs").update({status:"sending",last_error:`UNKNOWN_DELIVERY_STATE: ${error instanceof Error?error.message:"Provider request failed"}`,updated_at:new Date().toISOString()}).eq("id",job.id);return{sent:false,status:"manual_review",message:"حالة الإرسال غير مؤكدة؛ لن يُعاد الطلب تلقائيًا."}}
}

export async function processPendingSupplierJobs(limit=5):Promise<{success:boolean;message:string;processed:number;results:Array<{jobId:string;status:string;message:string}>}>{try{const{supabase}=await requireAdmin();const platformStatus=await readPlatformStatus(supabase);if(platformStatus.maintenanceMode||!platformStatus.supplierDispatchEnabled)return{success:false,message:"إرسال الطلبات إلى المورد متوقف من إعدادات المنصة.",processed:0,results:[]};const safeLimit=Math.min(20,Math.max(1,Math.floor(limit)));const{data,error}=await supabase.from("product_supplier_jobs").select("id,order_id,order_item_id,product_id,offer_id,provider_offer_id,supplier_product_id,input_values,status,attempts_count").eq("status","pending").order("created_at",{ascending:true}).limit(safeLimit).returns<SupplierJob[]>();if(error)throw error;const results=[];for(const job of data??[]){try{const result=await processJob(supabase,job);results.push({jobId:job.id,status:result.status,message:result.message})}catch(error){const message=error instanceof Error?error.message:"Invalid supplier job";await supabase.from("product_supplier_jobs").update({status:"failed",last_error:message,updated_at:new Date().toISOString()}).eq("id",job.id).eq("status","pending");await refreshAggregate(supabase,job);results.push({jobId:job.id,status:"failed",message})}}
  revalidatePath("/admin/orders");revalidatePath("/orders");revalidatePath("/notifications");return{success:true,message:results.length?`تمت معالجة ${results.length} مهمة مورد.`:"لا توجد مهام معلقة.",processed:results.length,results};}catch(error){return{success:false,message:error instanceof Error?error.message:"تعذر تشغيل مهام المورد.",processed:0,results:[]}}}

export async function syncSupplierJobStatuses():Promise<{success:boolean;message:string;processed:number}>{try{const{supabase}=await requireAdmin();const{data:jobs,error}=await supabase.from("product_supplier_jobs").select("id,order_id,order_item_id,product_id,offer_id,provider_offer_id,supplier_product_id,input_values,status,attempts_count,supplier_order_id").in("status",["supplier_pending","failed"]).not("supplier_order_id","is",null).limit(50);if(error)throw error;if(!jobs?.length)return{success:true,message:"لا توجد حالات مورد معلقة للمتابعة.",processed:0};const providerOrders=await getProviderOrders(1,100);const byId=new Map(providerOrders.flatMap(order=>[[order.fazerOrderId,order],[order.id,order]]));let processed=0;for(const raw of jobs){const match=byId.get(String(raw.supplier_order_id));if(!match)continue;const completed=["completed","success"].includes(match.status);const refunded=match.status==="refunded";const failed=["failed","cancelled","rejected"].includes(match.status);await supabase.from("product_supplier_jobs").update({status:completed?"completed":refunded?"refunded":failed?"failed":"supplier_pending",supplier_status:match.status,supplier_response:{order:match},completed_at:completed||refunded?new Date().toISOString():null,last_error:failed?`Provider status: ${match.status}`:null,updated_at:new Date().toISOString()}).eq("id",raw.id);if(refunded){const{data:orderJobs}=await supabase.from("product_supplier_jobs").select("status").eq("order_id",raw.order_id);if((orderJobs??[]).length>0&&(orderJobs??[]).every(job=>job.status==="refunded")){const{error:refundError}=await supabase.rpc("refund_product_order_after_supplier_confirmation",{p_order_id:raw.order_id,p_supplier_evidence:{provider:"flexy",matched_order_id:match.fazerOrderId,status:match.status,checked_at:new Date().toISOString()}});if(refundError)throw refundError}else await refreshAggregate(supabase,raw as SupplierJob)}else await refreshAggregate(supabase,raw as SupplierJob);processed++}revalidatePath("/admin/orders");revalidatePath("/orders");revalidatePath("/wallet");revalidatePath("/wallet/transactions");revalidatePath("/notifications");return{success:true,message:processed?`تم تحديث ${processed} حالة من Flexy، والاسترداد لا يتم إلا بعد حالة refunded مؤكدة.`:"لم نجد تحديثات مطابقة في أحدث طلبات Flexy.",processed}}catch(error){return{success:false,message:error instanceof Error?error.message:"تعذر تحديث حالات المورد.",processed:0}}}
