import { ActivityLogViewer,type ActivityLogItem } from "./ActivityLogViewer";
import { createClient } from "@/lib/supabase/server";

interface LogRow {id:string;user_id:string|null;actor_id:string|null;action:string;entity_type:string|null;entity_id:string|null;description:string|null;old_data:unknown;new_data:unknown;ip_address:string|null;created_at:string}
interface PersonRow {id:string;customer_id:string;full_name:string|null;email:string|null;role:string}
const secretPattern=/(password|secret|token|api.?key|authorization|cookie|credential)/i;
function safeData(value:unknown):unknown{if(Array.isArray(value))return value.map(safeData);if(value&&typeof value==="object"){return Object.fromEntries(Object.entries(value as Record<string,unknown>).filter(([key])=>!secretPattern.test(key)).map(([key,item])=>[key,safeData(item)]))}return value}

export default async function AdminActivityPage(){const supabase=await createClient();const{data:rows,error,count}=await supabase.from("activity_logs").select("id,user_id,actor_id,action,entity_type,entity_id,description,old_data,new_data,ip_address,created_at",{count:"exact"}).order("created_at",{ascending:false}).limit(500).returns<LogRow[]>();if(error)throw new Error("تعذر تحميل سجل النشاط.");const ids=[...new Set((rows??[]).flatMap(row=>[row.user_id,row.actor_id]).filter((id):id is string=>Boolean(id)))];const{data:people}=ids.length?await supabase.from("profiles").select("id,customer_id,full_name,email,role").in("id",ids).returns<PersonRow[]>():{data:[] as PersonRow[]};const byId=new Map((people??[]).map(person=>[person.id,person]));const logs:ActivityLogItem[]=(rows??[]).map(row=>{const actor=row.actor_id?byId.get(row.actor_id):null;const customer=row.user_id?byId.get(row.user_id):null;return{id:row.id,action:row.action,entityType:row.entity_type,entityId:row.entity_id,description:row.description,oldData:safeData(row.old_data),newData:safeData(row.new_data),ipAddress:row.ip_address,createdAt:row.created_at,actor:actor?{id:actor.id,name:actor.full_name??actor.email??actor.customer_id,role:actor.role}:null,customer:customer?{id:customer.id,customerId:customer.customer_id,name:customer.full_name??customer.email??customer.customer_id}:null}});return <ActivityLogViewer logs={logs} totalCount={count??logs.length}/>}
