import type { Metadata } from "next";
import type { ReactNode } from "react";
import { createClient } from "@/lib/supabase/server";
import { DEFAULT_KEYWORDS, SITE_NAME, absoluteUrl, jsonLd } from "@/lib/seo/site";

interface Category{id:string;slug:string;name_ar:string;name_en:string|null;description_ar:string|null;image_url:string|null}
async function load(slug:string){const db=await createClient();return (await db.from("store_categories").select("id,slug,name_ar,name_en,description_ar,image_url").eq("slug",slug).eq("active",true).maybeSingle<Category>()).data}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const category=await load(slug);const name=category?.name_ar??(slug==="games"?"شحن الألعاب":"الخدمات الرقمية");const description=category?.description_ar??`تصفح أفضل باقات ${name} المتاحة في مصر، بأسعار واضحة وتنفيذ سريع ودعم عربي من DevPlay.`;const title=`${name} في مصر — أسعار وباقات فورية`;const image=category?.image_url??absoluteUrl("/devplay-app-icon-512.png");return {title,description,keywords:[...DEFAULT_KEYWORDS,name,`${name} مصر`,`أسعار ${name}`],alternates:{canonical:absoluteUrl(`/categories/${slug}`)},openGraph:{title,description,url:absoluteUrl(`/categories/${slug}`),siteName:SITE_NAME,locale:"ar_EG",images:[{url:image,alt:name}]},twitter:{card:"summary_large_image",title,description,images:[image]}}}
export default async function CategorySeoLayout({children,params}:{children:ReactNode;params:Promise<{slug:string}>}){const {slug}=await params;const category=await load(slug);const name=category?.name_ar??(slug==="games"?"شحن الألعاب":"الخدمات الرقمية");const schema={"@context":"https://schema.org","@type":"CollectionPage",name,description:category?.description_ar??`باقات ${name} المتاحة على DevPlay`,url:absoluteUrl(`/categories/${slug}`),isPartOf:{"@id":`${absoluteUrl("/")}#store`}};return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html:jsonLd(schema)}}/>{children}</>}
