import "server-only";
import type { SupabaseClient } from "@supabase/supabase-js";

export interface PlatformStatus {
  maintenanceMode:boolean; ordersEnabled:boolean; depositsEnabled:boolean;
  walletTransfersEnabled:boolean; walletOperationsEnabled:boolean; supplierDispatchEnabled:boolean; maintenanceTitle:string; maintenanceMessage:string; expectedReturnAt:string|null; telegramUrl:string; whatsappUrl:string;
}
export const DEFAULT_PLATFORM_STATUS:PlatformStatus={maintenanceMode:false,ordersEnabled:true,depositsEnabled:true,walletTransfersEnabled:true,walletOperationsEnabled:true,supplierDispatchEnabled:true,maintenanceTitle:"DevPlay تحت التحديث حاليًا",maintenanceMessage:"نُجري حاليًا تحسينات مهمة على DevPlay. سنعود للعمل قريبًا.",expectedReturnAt:null,telegramUrl:"https://t.me/DevPlaySupport",whatsappUrl:"https://wa.me/201035966569"};
type Row={maintenance_mode:boolean;orders_enabled:boolean;deposits_enabled:boolean;wallet_transfers_enabled:boolean;wallet_operations_enabled:boolean;supplier_dispatch_enabled:boolean;maintenance_title:string|null;maintenance_message:string|null;expected_return_at:string|null;support_telegram_url:string|null;support_whatsapp_url:string|null};
export async function readPlatformStatus(db:SupabaseClient):Promise<PlatformStatus>{const{data,error}=await db.from("platform_settings").select("maintenance_mode,orders_enabled,deposits_enabled,wallet_transfers_enabled,wallet_operations_enabled,supplier_dispatch_enabled,maintenance_title,maintenance_message,expected_return_at,support_telegram_url,support_whatsapp_url").eq("id",1).maybeSingle<Row>();if(error||!data){if(error)console.error("Failed to read platform status",error.message);return DEFAULT_PLATFORM_STATUS}return{maintenanceMode:data.maintenance_mode,ordersEnabled:data.orders_enabled,depositsEnabled:data.deposits_enabled,walletTransfersEnabled:data.wallet_transfers_enabled,walletOperationsEnabled:data.wallet_operations_enabled,supplierDispatchEnabled:data.supplier_dispatch_enabled,maintenanceTitle:data.maintenance_title?.trim()||DEFAULT_PLATFORM_STATUS.maintenanceTitle,maintenanceMessage:data.maintenance_message?.trim()||DEFAULT_PLATFORM_STATUS.maintenanceMessage,expectedReturnAt:data.expected_return_at,telegramUrl:data.support_telegram_url?.trim()||DEFAULT_PLATFORM_STATUS.telegramUrl,whatsappUrl:data.support_whatsapp_url?.trim()||DEFAULT_PLATFORM_STATUS.whatsappUrl}}
export function operationMessage(operation:"orders"|"deposits"|"wallet_transfers"){return operation==="orders"?"إنشاء الطلبات متوقف مؤقتًا. يمكنك متابعة طلباتك السابقة من صفحة طلباتي.":operation==="deposits"?"طلبات إضافة الرصيد متوقفة مؤقتًا.":"تحويل الرصيد بين المحافظ متوقف مؤقتًا."}
export async function assertOperationEnabled(db:SupabaseClient,operation:"orders"|"deposits"|"wallet_transfers"){const status=await readPlatformStatus(db);if(status.maintenanceMode)throw new Error(status.maintenanceMessage);const enabled=operation==="orders"?status.ordersEnabled:operation==="deposits"?status.walletOperationsEnabled&&status.depositsEnabled:status.walletOperationsEnabled&&status.walletTransfersEnabled;if(!enabled)throw new Error(operationMessage(operation))}
