import { Activity, ArrowRight, Bell, CircleDollarSign, History, Mail, PackageSearch, Phone, ReceiptText, ShieldAlert, UserRound, WalletCards } from "lucide-react";
import Link from "next/link";
import { notFound } from "next/navigation";

import { createClient } from "@/lib/supabase/server";
import { CustomerSupportActions } from "./CustomerSupportActions";
import styles from "./customer.module.css";

interface Profile { id:string;customer_id:string;full_name:string|null;email:string|null;phone:string|null;avatar_url:string|null;status:string;role:string;points:number;customer_level:string;trust_score:number;suspicious_score:number;warnings_count:number;successful_orders_count:number;failed_orders_count:number;total_spent_usd:number|string;internal_notes:string|null;birth_date:string|null;birth_date_locked:boolean;created_at:string;last_login_at:string|null; }
interface Wallet { id:string;balance_usd:number|string;frozen_balance_usd:number|string;is_frozen:boolean;freeze_reason:string|null; }
interface Order { id:string;order_id:string;status:string;total_usd:number|string;discount_usd:number|string;created_at:string;supplier_status:string|null;failure_reason:string|null; }
interface Deposit { id:string;deposit_id:string;status:string;requested_currency:string;requested_amount:number|string;credit_usd:number|string;created_at:string;rejection_reason:string|null; }
interface WalletTx { id:string;type:string;amount_usd:number|string;balance_before_usd:number|string;balance_after_usd:number|string;description:string|null;reference_type:string|null;created_at:string; }
interface PointTx { id:string;type:string;direction:string;points:number;description:string|null;created_at:string; }
interface Log { id:string;action:string;entity_type:string|null;description:string|null;created_at:string;actor_id:string|null; }
interface Notice { id:string;type:string;title:string;message:string;is_read:boolean;created_at:string; }
interface SupportTicket { id:string;ticket_id:string;subject:string;status:string;created_at:string; }
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const dt=(v:string)=>new Intl.DateTimeFormat("ar-EG",{dateStyle:"medium",timeStyle:"short"}).format(new Date(v));
const usd=(v:number|string)=>`$${Number(v).toFixed(4)}`;
const statusLabel:Record<string,string>={active:"نشط",restricted:"مقيد",suspended:"موقوف",banned:"محظور",pending:"قيد الانتظار",under_review:"تحت المراجعة",approved:"مقبول",rejected:"مرفوض",completed:"مكتمل",failed:"فشل",cancelled:"ملغي"};

export default async function AdminCustomerPage({params}:{params:Promise<{id:string}>}){const{id}=await params;const supabase=await createClient();let profileQuery=supabase.from("profiles").select("id, customer_id, full_name, email, phone, avatar_url, status, role, points, customer_level, trust_score, suspicious_score, warnings_count, successful_orders_count, failed_orders_count, total_spent_usd, internal_notes, birth_date, birth_date_locked, created_at, last_login_at");profileQuery=uuid.test(id)?profileQuery.eq("id",id):profileQuery.eq("customer_id",id.toUpperCase());const{data:profile,error}=await profileQuery.maybeSingle<Profile>();if(error||!profile||profile.role!=="customer")notFound();
  const [walletR,ordersR,depositsR,walletTxR,logsR,noticesR,ticketsR]=await Promise.all([
    supabase.from("account_wallets").select("id, balance_usd, frozen_balance_usd, is_frozen, freeze_reason").eq("user_id",profile.id).maybeSingle<Wallet>(),
    supabase.from("product_orders").select("id, order_id, status, total_usd, discount_usd, created_at, supplier_status, failure_reason").eq("user_id",profile.id).order("created_at",{ascending:false}).limit(20).returns<Order[]>(),
    supabase.from("deposit_requests").select("id, deposit_id, status, requested_currency, requested_amount, credit_usd, created_at, rejection_reason").eq("user_id",profile.id).order("created_at",{ascending:false}).limit(20).returns<Deposit[]>(),
    supabase.from("account_wallet_transactions").select("id, type, amount_usd, balance_before_usd, balance_after_usd, description, reference_type, created_at").eq("user_id",profile.id).order("created_at",{ascending:false}).limit(30).returns<WalletTx[]>(),
    supabase.from("activity_logs").select("id, action, entity_type, description, created_at, actor_id").eq("user_id",profile.id).order("created_at",{ascending:false}).limit(30).returns<Log[]>(),
    supabase.from("notifications").select("id, type, title, message, is_read, created_at").eq("user_id",profile.id).order("created_at",{ascending:false}).limit(15).returns<Notice[]>(),
    supabase.from("support_tickets").select("id,ticket_id,subject,status,created_at").eq("user_id",profile.id).order("created_at",{ascending:false}).limit(20).returns<SupportTicket[]>(),
  ]);const wallet=walletR.data;const orders=ordersR.data??[];const deposits=depositsR.data??[];const walletTx=walletTxR.data??[];const logs=logsR.data??[];const notices=noticesR.data??[];const tickets=ticketsR.data??[];
  return <main className={styles.page}><div className={styles.breadcrumb}><Link href="/admin/users"><ArrowRight size={14}/> العملاء</Link><span>{profile.customer_id}</span></div><header className={styles.hero}><div className={styles.identity}><span className={styles.avatar}>{profile.avatar_url?<img src={profile.avatar_url} alt={profile.full_name??profile.customer_id}/>:<UserRound size={30}/>}</span><div><small>CUSTOMER 360°</small><h1>{profile.full_name??"عميل DevPlay"}</h1><p>{profile.customer_id} · {profile.id}</p></div></div><div className={styles.heroActions}>{profile.phone&&<a href={`https://wa.me/${profile.phone.replace(/\D/g,"")}`}><Phone size={15}/> واتساب</a>}{profile.email&&<a href={`mailto:${profile.email}`}><Mail size={15}/> بريد</a>}<Link href={`/admin/orders/manual?customer=${profile.id}`}><PackageSearch size={15}/> إنشاء طلب يدوي</Link></div></header>
  <section className={styles.stats}><article><WalletCards/><span>الرصيد</span><strong>{usd(wallet?.balance_usd??0)}</strong><small>{wallet?.is_frozen?"المحفظة مجمدة":"متاح للاستخدام"}</small></article><article><PackageSearch/><span>الطلبات</span><strong>{orders.length}</strong><small>{profile.successful_orders_count} ناجح</small></article><article><ReceiptText/><span>الإيداعات</span><strong>{deposits.length}</strong><small>{deposits.filter(d=>d.status==="pending").length} قيد المراجعة</small></article><article><CircleDollarSign/><span>إجمالي الإنفاق</span><strong>{usd(profile.total_spent_usd)}</strong><small>Trust {profile.trust_score}%</small></article></section>
  <div className={styles.dashboard}><div className={styles.mainColumn}><Panel title="الطلبات الأخيرة" icon={<PackageSearch size={17}/>} count={orders.length}>{orders.length?<div className={styles.rows}>{orders.map(o=><Link href={`/admin/orders?order=${o.order_id}`} className={styles.row} key={o.id}><div><strong>{o.order_id}</strong><small>{dt(o.created_at)}</small></div><div><span className={styles.status}>{statusLabel[o.status]??o.status}</span><strong>{usd(o.total_usd)}</strong></div>{o.failure_reason&&<p>{o.failure_reason}</p>}</Link>)}</div>:<Empty/>}</Panel>
  <Panel title="طلبات الإيداع" icon={<ReceiptText size={17}/>} count={deposits.length}>{deposits.length?<div className={styles.rows}>{deposits.map(d=><Link href="/admin/deposits" className={styles.row} key={d.id}><div><strong>{d.deposit_id}</strong><small>{dt(d.created_at)}</small></div><div><span className={styles.status}>{statusLabel[d.status]??d.status}</span><strong>{d.requested_amount} {d.requested_currency}</strong></div>{d.rejection_reason&&<p>{d.rejection_reason}</p>}</Link>)}</div>:<Empty/>}</Panel>
  <Panel title="حركات المحفظة" icon={<History size={17}/>} count={walletTx.length}>{walletTx.length?<div className={styles.rows}>{walletTx.map(t=><div className={styles.row} key={t.id}><div><strong>{t.type}</strong><small>{dt(t.created_at)} · {t.description??t.reference_type??"حركة محفظة"}</small></div><div><strong>{usd(t.amount_usd)}</strong><small>{usd(t.balance_before_usd)} ← {usd(t.balance_after_usd)}</small></div></div>)}</div>:<Empty/>}</Panel>
  <Panel title="تذاكر خدمة العملاء" icon={<Bell size={17}/>} count={tickets.length}>{tickets.length?<div className={styles.rows}>{tickets.map(t=><Link href="/admin/support" className={styles.row} key={t.id}><div><strong>{t.ticket_id} - {t.subject}</strong><small>{dt(t.created_at)}</small></div><span className={styles.status}>{t.status}</span></Link>)}</div>:<Empty/>}</Panel></div>
  <aside className={styles.sideColumn}><CustomerSupportActions userId={profile.id} birthDate={profile.birth_date}/><Panel title="حالة الحساب" icon={<ShieldAlert size={17}/>}><div className={styles.info}><span><small>الحالة</small><strong>{statusLabel[profile.status]??profile.status}</strong></span><span><small>تحذيرات</small><strong>{profile.warnings_count}</strong></span><span><small>Suspicious</small><strong>{profile.suspicious_score}</strong></span><span><small>آخر دخول</small><strong>{profile.last_login_at?dt(profile.last_login_at):"غير متاح"}</strong></span></div>{profile.internal_notes&&<p className={styles.note}>{profile.internal_notes}</p>}<Link className={styles.manage} href={`/admin/users?customer=${profile.customer_id}`}>فتح أدوات الحالة والتجميد</Link></Panel>
  <Panel title="الإشعارات الأخيرة" icon={<Bell size={17}/>} count={notices.length}>{notices.length?<div className={styles.miniRows}>{notices.map(n=><div key={n.id}><span>{n.title}<small>{dt(n.created_at)}</small></span><i className={n.is_read?styles.read:styles.unread}/></div>)}</div>:<Empty/>}</Panel><Panel title="سجل النشاط" icon={<Activity size={17}/>} count={logs.length}>{logs.length?<div className={styles.miniRows}>{logs.slice(0,12).map(l=><div key={l.id}><span>{l.description??l.action}<small>{dt(l.created_at)}</small></span></div>)}</div>:<Empty/>}</Panel></aside></div></main>}
function Panel({title,icon,count,children}:{title:string;icon:React.ReactNode;count?:number;children:React.ReactNode}){return <section className={styles.panel}><header><span>{icon}</span><strong>{title}</strong>{typeof count==="number"&&<small>{count}</small>}</header>{children}</section>}
function Empty(){return <div className={styles.empty}>لا توجد بيانات مسجلة.</div>}
