import type { Metadata } from "next";
import type { ReactNode } from "react";
import { createClient } from "@/lib/supabase/server";
import { DEFAULT_KEYWORDS, SITE_NAME, absoluteUrl, jsonLd } from "@/lib/seo/site";

interface Offer{id:string;name_ar:string;supplier_price_usd:number|string;profit_usd:number|string;manual_selling_price_usd:number|string|null;available:boolean;active:boolean;stock:number|null}
interface Product{id:string;slug:string;name_ar:string;name_en:string|null;short_description_ar:string|null;description_ar:string|null;image_url:string|null;updated_at:string;category:{name_ar:string;slug:string}|Array<{name_ar:string;slug:string}>|null;store_product_offers:Offer[]|null}
function relation<T>(value:T|T[]|null){return Array.isArray(value)?value[0]??null:value}
async function load(slug:string){const db=await createClient();const [product,settings]=await Promise.all([db.from("store_products").select("id,slug,name_ar,name_en,short_description_ar,description_ar,image_url,updated_at,category:store_categories(name_ar,slug),store_product_offers(id,name_ar,supplier_price_usd,profit_usd,manual_selling_price_usd,available,active,stock)").eq("slug",slug).eq("active",true).maybeSingle<Product>(),db.from("platform_settings").select("usd_to_egp_rate").eq("id",1).maybeSingle<{usd_to_egp_rate:number|string}>()]);return {product:product.data,rate:Number(settings.data?.usd_to_egp_rate??57)}}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const {product,rate}=await load(slug);if(!product)return {title:"المنتج غير متاح",robots:{index:false,follow:false}};const offers=(product.store_product_offers??[]).filter(o=>o.active&&o.available&&(o.stock===null||o.stock>0));const prices=offers.map(o=>(o.manual_selling_price_usd===null?Number(o.supplier_price_usd)+Number(o.profit_usd):Number(o.manual_selling_price_usd))*rate);const lowest=prices.length?Math.min(...prices):null;const description=product.short_description_ar??`اشحن ${product.name_ar} بأمان وسرعة من DevPlay. اختر الباقة وأدخل بيانات الحساب وتابع طلبك لحظة بلحظة.`;const title=`شحن ${product.name_ar}${lowest!==null?` يبدأ من ${lowest.toLocaleString("ar-EG",{maximumFractionDigits:2})} ج.م`:""}`;const image=product.image_url??absoluteUrl("/devplay-app-icon-512.png");return {title,description,keywords:[...DEFAULT_KEYWORDS,product.name_ar,product.name_en??"",`شحن ${product.name_ar}`,`${product.name_ar} مصر`].filter(Boolean),alternates:{canonical:absoluteUrl(`/products/${product.slug}`)},openGraph:{type:"website",locale:"ar_EG",siteName:SITE_NAME,title,description,url:absoluteUrl(`/products/${product.slug}`),images:[{url:image,alt:product.name_ar}]},twitter:{card:"summary_large_image",title,description,images:[image]},robots:{index:offers.length>0,follow:true,googleBot:{index:offers.length>0,follow:true,"max-image-preview":"large","max-snippet":-1,"max-video-preview":-1}}}}
export default async function ProductSeoLayout({children,params}:{children:ReactNode;params:Promise<{slug:string}>}){const {slug}=await params;const {product,rate}=await load(slug);if(!product)return children;const category=relation(product.category);const available=(product.store_product_offers??[]).filter(o=>o.active&&o.available&&(o.stock===null||o.stock>0));const prices=available.map(o=>(o.manual_selling_price_usd===null?Number(o.supplier_price_usd)+Number(o.profit_usd):Number(o.manual_selling_price_usd))*rate);const schema={"@context":"https://schema.org","@type":"Product","@id":`${absoluteUrl(`/products/${product.slug}`)}#product`,name:product.name_ar,alternateName:product.name_en??undefined,image:product.image_url?[product.image_url]:[absoluteUrl("/devplay-app-icon-512.png")],description:product.short_description_ar??product.description_ar??`شحن ${product.name_ar} من DevPlay`,brand:{"@type":"Brand",name:"DevPlay"},category:category?.name_ar,sku:product.id,offers:prices.length?{"@type":"AggregateOffer",url:absoluteUrl(`/products/${product.slug}`),priceCurrency:"EGP",lowPrice:Math.min(...prices).toFixed(2),highPrice:Math.max(...prices).toFixed(2),offerCount:available.length,availability:"https://schema.org/InStock"}:undefined};const breadcrumb={"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"الرئيسية",item:absoluteUrl("/")},{"@type":"ListItem",position:2,name:category?.name_ar??"المنتجات",item:category?absoluteUrl(`/categories/${category.slug}`):absoluteUrl("/products")},{"@type":"ListItem",position:3,name:product.name_ar,item:absoluteUrl(`/products/${product.slug}`)}]};return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html:jsonLd(schema)}}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:jsonLd(breadcrumb)}}/>{children}</>}
