import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import { NextRequest } from "next/server";
import { createClient } from "@/lib/supabase/server";
export const runtime="nodejs";
interface Tx{id:string;type:string;amount_usd:number|string;balance_before_usd:number|string;balance_after_usd:number|string;reference_type:string|null;description:string|null;created_at:string}
function safe(value:string|null|undefined){return (value??"").replace(/[^\x20-\x7E]/g," ").slice(0,72)}
export async function GET(request:NextRequest){
 const s=await createClient();const{data:{user}}=await s.auth.getUser();if(!user)return new Response("Unauthorized",{status:401});
 const id=request.nextUrl.searchParams.get("transactionId");let query=s.from("account_wallet_transactions").select("id,type,amount_usd,balance_before_usd,balance_after_usd,reference_type,description,created_at").eq("user_id",user.id).order("created_at",{ascending:false}).limit(id?1:10);if(id)query=query.eq("id",id);
 const[{data:rows,error},{data:profile}]=await Promise.all([query.returns<Tx[]>(),s.from("profiles").select("customer_id,full_name").eq("id",user.id).single<{customer_id:string;full_name:string|null}>()]);if(error||!rows?.length)return new Response("No transactions found",{status:404});
 const doc=await PDFDocument.create();const regular=await doc.embedFont(StandardFonts.Helvetica);const bold=await doc.embedFont(StandardFonts.HelveticaBold);const page=doc.addPage([595,842]);const{width,height}=page.getSize();
 page.drawRectangle({x:0,y:height-105,width,height:105,color:rgb(.12,.07,.23)});page.drawText("DEVPLAY",{x:42,y:height-60,size:25,font:bold,color:rgb(.65,.45,1)});page.drawText(id?"TRANSACTION RECEIPT":"WALLET STATEMENT",{x:42,y:height-84,size:11,font:bold,color:rgb(1,1,1)});
 page.drawText(`Customer: ${profile?.customer_id??user.id}`,{x:42,y:height-130,size:10,font:bold,color:rgb(.15,.15,.2)});page.drawText(`Generated: ${new Date().toISOString().replace("T"," ").slice(0,19)} UTC`,{x:320,y:height-130,size:8,font:regular,color:rgb(.4,.4,.45)});
 let y=height-170;for(const tx of rows){const before=Number(tx.balance_before_usd),after=Number(tx.balance_after_usd),credit=after>=before;page.drawRectangle({x:38,y:y-54,width:519,height:62,color:rgb(.965,.96,.98),borderColor:rgb(.86,.82,.92),borderWidth:1});page.drawText(credit?"CREDIT":"DEBIT",{x:50,y:y-17,size:9,font:bold,color:credit?rgb(.08,.55,.3):rgb(.75,.15,.2)});page.drawText(`${credit?"+":"-"}$${Number(tx.amount_usd).toFixed(4)}`,{x:445,y:y-17,size:11,font:bold,color:rgb(.15,.1,.25)});page.drawText(`${new Date(tx.created_at).toISOString().replace("T"," ").slice(0,19)} UTC`,{x:50,y:y-34,size:8,font:regular,color:rgb(.4,.4,.45)});page.drawText(safe(tx.description)||safe(tx.reference_type)||tx.type,{x:50,y:y-48,size:8,font:regular,color:rgb(.25,.25,.3)});page.drawText(`Balance: $${before.toFixed(4)}  >  $${after.toFixed(4)}`,{x:340,y:y-39,size:8,font:regular,color:rgb(.4,.35,.5)});y-=72}
 page.drawText("Generated securely by DevPlay Top Up - Shahd Elbary",{x:42,y:32,size:8,font:regular,color:rgb(.45,.45,.5)});const bytes=await doc.save();const filename=id?`devplay-receipt-${id.slice(0,8)}.pdf`:`devplay-wallet-statement.pdf`;return new Response(Buffer.from(bytes),{headers:{"Content-Type":"application/pdf","Content-Disposition":`attachment; filename="${filename}"`,"Cache-Control":"no-store"}})
}
