"use client";
import{CheckCircle2,KeyRound,LoaderCircle,Plus,Save,Trash2}from"lucide-react";
import{useRouter}from"next/navigation";
import{useState,useTransition}from"react";
import{updateProductRedemptionSettings}from"@/app/admin/products/[id]/offer-actions";
export function ProductRedemptionSettings({productId,initial}:{productId:string;initial:{steps:string[];url:string;assistedEnabled:boolean;accountLabel:string;accountPlaceholder:string}}){
 const router=useRouter();const[steps,setSteps]=useState(initial.steps.length?initial.steps:[""]);const[urlEnabled,setUrlEnabled]=useState(Boolean(initial.url));const[url,setUrl]=useState(initial.url);const[assistedEnabled,setAssistedEnabled]=useState(initial.assistedEnabled);const[accountLabel,setAccountLabel]=useState(initial.accountLabel||"معرف الحساب / Player ID");const[accountPlaceholder,setAccountPlaceholder]=useState(initial.accountPlaceholder||"اكتب معرف الحساب بدقة");const[result,setResult]=useState<{success:boolean;message:string}|null>(null);const[pending,startTransition]=useTransition();
 function updateStep(index:number,value:string){setSteps(current=>current.map((step,i)=>i===index?value:step))}function save(){setResult(null);startTransition(async()=>{const response=await updateProductRedemptionSettings({productId,steps,redemptionUrl:urlEnabled?url:null,assistedEnabled,accountLabel,accountPlaceholder});setResult(response);if(response.success)router.refresh()})}
 return <section style={{display:"grid",gap:12,padding:14,border:"1px solid var(--primary-border)",borderRadius:14,background:"var(--primary-soft)"}}><header style={{display:"flex",gap:9,alignItems:"flex-start"}}><KeyRound size={19} style={{color:"var(--primary)"}}/><div><strong style={{fontSize:11}}>نافذة استرداد الأكواد لكل باقات المنتج</strong><p style={{margin:"4px 0 0",color:"var(--muted)",fontSize:8}}>الخطوات والرابط وخدمة التنفيذ ستظهر لكل باقات المنتج الحالية والجديدة.</p></div></header>
 <div style={{display:"grid",gap:8}}><div style={{display:"flex",justifyContent:"space-between",gap:8,alignItems:"center"}}><strong style={{fontSize:9}}>خطوات الاسترداد</strong><button type="button" disabled={steps.length>=10} onClick={()=>setSteps(current=>[...current,""])} style={{minHeight:34,display:"inline-flex",alignItems:"center",gap:5,paddingInline:10,border:"1px solid var(--primary-border)",borderRadius:9,background:"var(--surface)",color:"var(--primary)",fontWeight:900}}><Plus size={14}/> إضافة خطوة</button></div>{steps.map((step,index)=><label key={index} style={{display:"grid",gridTemplateColumns:"34px minmax(0,1fr) 36px",gap:7,alignItems:"center"}}><strong style={{display:"grid",width:30,height:30,placeItems:"center",borderRadius:"50%",background:"var(--primary)",color:"#fff",fontSize:9}}>{index+1}</strong><textarea rows={2} value={step} onChange={e=>updateStep(index,e.target.value)} placeholder={`اكتبي الخطوة ${index+1}`}/><button type="button" aria-label={`حذف الخطوة ${index+1}`} disabled={steps.length===1} onClick={()=>setSteps(current=>current.filter((_,i)=>i!==index))} style={{width:34,height:34,display:"grid",placeItems:"center",border:"1px solid var(--danger)",borderRadius:9,background:"transparent",color:"var(--danger)"}}><Trash2 size={14}/></button></label>)}</div>
 <section style={{display:"grid",gap:8,padding:10,border:"1px solid var(--border)",borderRadius:11,background:"var(--surface)"}}><label style={{display:"flex",gap:7,alignItems:"center",fontSize:8,fontWeight:800}}><input type="checkbox" checked={urlEnabled} onChange={e=>setUrlEnabled(e.target.checked)}/> إضافة زر فتح موقع الاسترداد الرسمي</label>{urlEnabled&&<input dir="ltr" type="url" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://..."/>}</section>
 <section style={{display:"grid",gap:8,padding:10,border:"1px solid var(--border)",borderRadius:11,background:"var(--surface)"}}><label style={{display:"flex",gap:7,alignItems:"center",fontSize:8,fontWeight:800}}><input type="checkbox" checked={assistedEnabled} onChange={e=>setAssistedEnabled(e.target.checked)}/> تفعيل «طلب تنفيذ الكود بواسطة DevPlay»</label>{assistedEnabled&&<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(190px,1fr))",gap:8}}><label style={{display:"grid",gap:5,fontSize:8}}><span>اسم البيانات المطلوبة</span><input value={accountLabel} onChange={e=>setAccountLabel(e.target.value)} placeholder="Player ID / Username / رابط الحساب"/></label><label style={{display:"grid",gap:5,fontSize:8}}><span>النص داخل الخانة</span><input value={accountPlaceholder} onChange={e=>setAccountPlaceholder(e.target.value)} placeholder="اكتب البيانات بدقة"/></label></div>}</section>
 {result&&<p style={{margin:0,color:result.success?"var(--success)":"var(--danger)",fontSize:8,fontWeight:800}}>{result.success&&<CheckCircle2 size={14} style={{verticalAlign:"middle",marginInlineEnd:5}}/>}{result.message}</p>}<button type="button" disabled={pending} onClick={save} style={{width:"fit-content",minHeight:40,display:"inline-flex",alignItems:"center",gap:7,paddingInline:14,border:0,borderRadius:10,background:"var(--primary)",color:"#fff",fontWeight:900}}>{pending?<LoaderCircle size={16}/>:<Save size={16}/>} حفظ النافذة لكل باقات المنتج</button></section>
}
