begin;
create table if not exists public.support_tickets(
 id uuid primary key default gen_random_uuid(), ticket_number bigint generated always as identity unique,
 ticket_id text generated always as ('DP-S-'||lpad(ticket_number::text,6,'0')) stored unique,
 user_id uuid not null references public.profiles(id), category text not null check(category in('deposit','order','wallet','account','suggestion','other')),
 subject text not null, status text not null default 'open' check(status in('open','in_progress','waiting_customer','resolved','closed')),
 priority text not null default 'normal' check(priority in('low','normal','high','urgent')), assigned_to uuid references public.profiles(id),
 created_at timestamptz not null default now(),updated_at timestamptz not null default now(),resolved_at timestamptz
);
create table if not exists public.support_ticket_messages(
 id uuid primary key default gen_random_uuid(),ticket_id uuid not null references public.support_tickets(id) on delete cascade,
 sender_id uuid not null references public.profiles(id),sender_role text not null check(sender_role in('customer','support','admin','super_admin','owner')),
 message text not null,created_at timestamptz not null default now()
);
create index if not exists support_tickets_user_created_idx on public.support_tickets(user_id,created_at desc);
create index if not exists support_messages_ticket_created_idx on public.support_ticket_messages(ticket_id,created_at);
alter table public.support_tickets enable row level security;alter table public.support_ticket_messages enable row level security;
drop policy if exists support_tickets_customer_select on public.support_tickets;create policy support_tickets_customer_select on public.support_tickets for select to authenticated using(user_id=auth.uid() or exists(select 1 from public.profiles p where p.id=auth.uid() and p.role::text in('support','admin','super_admin','owner')));
drop policy if exists support_messages_participant_select on public.support_ticket_messages;create policy support_messages_participant_select on public.support_ticket_messages for select to authenticated using(exists(select 1 from public.support_tickets t where t.id=public.support_ticket_messages.ticket_id and(t.user_id=auth.uid() or exists(select 1 from public.profiles p where p.id=auth.uid() and p.role::text in('support','admin','super_admin','owner')))));
create or replace function public.create_support_ticket(p_category text,p_subject text,p_message text)returns public.support_tickets language plpgsql security definer set search_path to '' as $f$ declare v_user uuid:=auth.uid();v_ticket public.support_tickets;begin if v_user is null then raise exception 'Authentication required';end if;if p_category not in('deposit','order','wallet','account','suggestion','other')then raise exception 'Invalid category';end if;if length(trim(p_subject))<3 or length(trim(p_subject))>120 then raise exception 'Invalid subject';end if;if length(trim(p_message))<5 or length(trim(p_message))>3000 then raise exception 'Invalid message';end if;insert into public.support_tickets(user_id,category,subject)values(v_user,p_category,trim(p_subject))returning * into v_ticket;insert into public.support_ticket_messages(ticket_id,sender_id,sender_role,message)values(v_ticket.id,v_user,'customer',trim(p_message));insert into public.activity_logs(user_id,actor_id,action,entity_type,entity_id,description)values(v_user,v_user,'support_ticket_created','support_ticket',v_ticket.id,'Customer created support ticket');return v_ticket;end;$f$;
create or replace function public.reply_support_ticket(p_ticket_id uuid,p_message text,p_status text default 'waiting_customer')returns void language plpgsql security definer set search_path to '' as $f$ declare v_admin public.profiles;v_ticket public.support_tickets;begin select * into v_admin from public.profiles where id=auth.uid() and role::text in('support','admin','super_admin','owner') and status::text='active';if not found then raise exception 'Admin permission required';end if;if length(trim(p_message))<2 or length(trim(p_message))>3000 then raise exception 'Invalid reply';end if;if p_status not in('in_progress','waiting_customer','resolved','closed')then raise exception 'Invalid status';end if;select * into v_ticket from public.support_tickets where id=p_ticket_id for update;if not found then raise exception 'Ticket not found';end if;insert into public.support_ticket_messages(ticket_id,sender_id,sender_role,message)values(v_ticket.id,v_admin.id,v_admin.role::text,trim(p_message));update public.support_tickets set status=p_status,assigned_to=v_admin.id,updated_at=now(),resolved_at=case when p_status='resolved' then now() else resolved_at end where id=v_ticket.id;insert into public.notifications(user_id,type,title,message,entity_type,entity_id,action_url)values(v_ticket.user_id,'support_ticket_reply','رد جديد من خدمة العملاء',format('تم الرد على تذكرتك %s: %s',v_ticket.ticket_id,left(trim(p_message),140)),'support_ticket',v_ticket.id,'/support');end;$f$;
revoke all on function public.create_support_ticket(text,text,text) from public;grant execute on function public.create_support_ticket(text,text,text) to authenticated;
revoke all on function public.reply_support_ticket(uuid,text,text) from public;grant execute on function public.reply_support_ticket(uuid,text,text) to authenticated;
commit;
