"use client";

import { LoaderCircle, Play, ShieldAlert } from "lucide-react";
import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { processPendingSupplierJobs } from "@/app/admin/orders/provider-actions";
import { syncSupplierStatusesWithServer as syncSupplierJobStatuses } from "@/app/admin/orders/automatic-actions";

export function SupplierJobsRunner(){const router=useRouter();const[pending,startTransition]=useTransition();const[message,setMessage]=useState<string|null>(null);function run(action:()=>Promise<{message:string}>){startTransition(async()=>{const result=await action();setMessage(result.message);router.refresh()})}return <section className="supplierRunner"><div><span><Play size={17}/></span><div><strong>تشغيل ومتابعة Flexy</strong><small>إرسال المهام الجديدة أو جلب حالات الطلبات التي تنتظر المورد.</small></div></div><div className="runnerActions"><button type="button" disabled={pending} onClick={()=>run(()=>processPendingSupplierJobs(5))}>{pending?<LoaderCircle className="runnerSpin" size={16}/>:<Play size={16}/>} إرسال 5 مهام</button><button className="runnerSecondary" type="button" disabled={pending} onClick={()=>run(syncSupplierJobStatuses)}><ShieldAlert size={16}/> تحديث الحالات</button></div>{message&&<p><ShieldAlert size={14}/>{message}</p>}<style>{`.supplierRunner{display:grid;grid-template-columns:minmax(0,1fr) auto;align-items:center;gap:10px;margin-bottom:12px;padding:12px;border:1px solid var(--primary-border);border-radius:14px;background:var(--primary-soft)}.supplierRunner>div{display:flex;align-items:center;gap:9px}.supplierRunner>div>span{display:grid;width:34px;height:34px;place-items:center;border-radius:10px;background:var(--surface);color:var(--primary)}.supplierRunner>div>div{display:grid;gap:2px}.supplierRunner strong{font-size:10px}.supplierRunner small{color:var(--muted);font-size:7px}.runnerActions{display:flex!important;gap:6px}.supplierRunner button{display:flex;min-height:38px;align-items:center;gap:6px;padding-inline:12px;border:1px solid var(--primary-border);border-radius:10px;background:var(--primary);color:#fff;font:inherit;font-size:8px;font-weight:900}.supplierRunner .runnerSecondary{background:var(--surface);color:var(--primary)}.supplierRunner p{grid-column:1/-1;display:flex;align-items:center;gap:5px;margin:0;color:var(--muted);font-size:7px}.runnerSpin{animation:runnerSpin .8s linear infinite}@keyframes runnerSpin{to{transform:rotate(360deg)}}@media(max-width:700px){.supplierRunner{grid-template-columns:1fr}.runnerActions{display:grid!important;grid-template-columns:1fr 1fr}.supplierRunner button{justify-content:center}}`}</style></section>}
